// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN_63lfoWIDaskeVfrn-Zbs3g_uKvvWC0',
    appId: '1:239155399192:web:e6bae0b9b441c02b75516d',
    messagingSenderId: '239155399192',
    projectId: 'krix-d8fe2',
    authDomain: 'krix-d8fe2.firebaseapp.com',
    storageBucket: 'krix-d8fe2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwBoeufCWGxH7q4vzURLk8AULfwqW6Xlc',
    appId: '1:239155399192:android:644ef78f866a2df475516d',
    messagingSenderId: '239155399192',
    projectId: 'krix-d8fe2',
    storageBucket: 'krix-d8fe2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX4aancNnUxIwQyOykN5i_VAu8qwEclU0',
    appId: '1:239155399192:ios:5a68c0a18eaaeb8175516d',
    messagingSenderId: '239155399192',
    projectId: 'krix-d8fe2',
    storageBucket: 'krix-d8fe2.appspot.com',
    iosClientId:
        '239155399192-i902hv55bi6sc20ghh8isugnhrsaa8h5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX4aancNnUxIwQyOykN5i_VAu8qwEclU0',
    appId: '1:239155399192:ios:5a68c0a18eaaeb8175516d',
    messagingSenderId: '239155399192',
    projectId: 'krix-d8fe2',
    storageBucket: 'krix-d8fe2.appspot.com',
    iosClientId:
        '239155399192-i902hv55bi6sc20ghh8isugnhrsaa8h5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
